// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnnouncement():Promise<string>;

export function Open(arg1:string):Promise<void>;

export function ProxyList():Promise<Array<string>>;

export function Switch(arg1:boolean,arg2:string,arg3:boolean):Promise<string>;

export function Version():Promise<string>;
